# Generated by Django 5.2.1 on 2025-06-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegistroProfesional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("cedula_identidad", models.CharField(max_length=20)),
                ("usuario", models.CharField(max_length=100, unique=True)),
                ("contrasena", models.CharField(max_length=128)),
                (
                    "especialidad",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rol", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                ("id_hospital", models.IntegerField()),
            ],
        ),
    ]
